"""
Django settings for cba_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import importlib.util
import logging
from datetime import timedelta

from django.core.exceptions import ImproperlyConfigured

try:
    import dj_database_url  # type: ignore
except Exception:  # pragma: no cover
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name: str, default: bool = False) -> bool:
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in {"1", "true", "yes", "y", "on"}


def _env_list(name: str, default: list[str] | None = None) -> list[str]:
    val = os.environ.get(name)
    if not val:
        return default or []
    return [x.strip() for x in val.split(",") if x.strip()]


def _module_available(module_name: str) -> bool:
    try:
        return importlib.util.find_spec(module_name) is not None
    except Exception:
        return False


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", True)

IS_PRODUCTION = not DEBUG

# Cloudinary
# El usuario pidió que los uploads (avatar/guía) se guarden sí o sí en Cloudinary.
# En producción, si no está configurado CLOUDINARY_URL, preferimos fallar explícitamente
# para evitar “guardados” en disco efímero del PaaS.
ALLOW_NO_CLOUDINARY_IN_PROD = _env_bool("ALLOW_NO_CLOUDINARY_IN_PROD", False)
if IS_PRODUCTION and not os.environ.get("CLOUDINARY_URL") and not ALLOW_NO_CLOUDINARY_IN_PROD:
    raise ImproperlyConfigured(
        "Cloudinary no está configurado en producción. Define CLOUDINARY_URL en el entorno. "
        "(Si deseas deshabilitar esta validación explícitamente, setea ALLOW_NO_CLOUDINARY_IN_PROD=true.)"
    )

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "testserver"],
)

# Render expone el hostname externo en esta variable.
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    # UI moderna para allauth (Tailwind/DaisyUI)
    'allauth_ui',
    'widget_tweaks',
    'slippers',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Auth moderno
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Seguridad login
    'axes',

    'adminlte3',
    'cba_app',
]

# Provider social (Google) requiere cryptography (y wheels compatibles). Si no está disponible,
# no lo activamos para evitar romper el arranque/migraciones en entornos limitados.
if _module_available("cryptography"):
    INSTALLED_APPS.append('allauth.socialaccount.providers.google')

# Cloudinary (media) opcional: se activa solo si CLOUDINARY_URL está configurado.
if os.environ.get("CLOUDINARY_URL"):
    if not (_module_available("cloudinary") and _module_available("cloudinary_storage")):
        raise ImproperlyConfigured(
            "CLOUDINARY_URL está configurado pero faltan dependencias. "
            "Instala 'django-cloudinary-storage' y sus requisitos en el deploy."
        )

    INSTALLED_APPS = [
        "cloudinary",
        "cloudinary_storage",
        *INSTALLED_APPS,
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]

# En producción (DEBUG=False) necesitamos servir estáticos. En Render, lo más simple es WhiteNoise.
# Si WhiteNoise no está instalado, preferimos fallar explícitamente (en vez de servir la web sin CSS/JS).
if not DEBUG:
    try:
        import whitenoise  # noqa: F401
    except Exception as exc:  # pragma: no cover
        raise ImproperlyConfigured(
            "WhiteNoise es requerido cuando DJANGO_DEBUG=false. "
            "Instala dependencias con `pip install -r requirements.txt`."
        ) from exc

    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
    # Fallback: permite servir desde finders si collectstatic no se ejecutó por alguna razón.
    WHITENOISE_USE_FINDERS = True

MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Permite embebidos (iframes) dentro del mismo sitio.
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'cba_project.urls'
SITE_ID = int(os.environ.get("DJANGO_SITE_ID", "1"))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cba_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL and dj_database_url is not None:
    DATABASES["default"] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        ssl_require=not DEBUG,
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True

# Logging
# En producción (DEBUG=False) Django no imprime automáticamente tracebacks a consola.
# Esto hace difícil depurar en Render. Forzamos logging de errores HTTP 500 a stdout/stderr.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# Auth
LOGIN_URL = "/cuentas/ingresar/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/cuentas/ingresar/"

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

_email_host = (os.environ.get("DJANGO_EMAIL_HOST") or "").strip()
_sendgrid_api_key = (os.environ.get("SENDGRID_API_KEY") or "").strip()
_default_from_email = (os.environ.get("DEFAULT_FROM_EMAIL") or os.environ.get("DJANGO_DEFAULT_FROM_EMAIL") or "").strip()

EMAIL_TIMEOUT = int(os.environ.get("DJANGO_EMAIL_TIMEOUT", "10"))

# En algunos PaaS el SMTP puede bloquearse/ser lento. Si hay SENDGRID_API_KEY,
# preferimos usar la API HTTP de SendGrid para evitar timeouts de workers.
SENDGRID_USE_HTTP_API = _env_bool(
    "SENDGRID_USE_HTTP_API",
    default=bool(_sendgrid_api_key) and IS_PRODUCTION,
)

# Exponer para el adapter (no imprimirlo en logs).
SENDGRID_API_KEY = _sendgrid_api_key

_smtp_configured = bool(_sendgrid_api_key) or bool(_email_host)

# En producción, si se espera verificación de email / reset de contraseña, necesitamos un backend real.
# Esto evita un despliegue que "parece" funcionar pero nunca entrega correos.
ALLOW_NO_EMAIL_IN_PROD = _env_bool("ALLOW_NO_EMAIL_IN_PROD", False)
if IS_PRODUCTION and not _smtp_configured and not ALLOW_NO_EMAIL_IN_PROD:
    raise ImproperlyConfigured(
        "Email no configurado en producción. Define SENDGRID_API_KEY (recomendado) o "
        "DJANGO_EMAIL_HOST (+ DJANGO_EMAIL_HOST_USER/DJANGO_EMAIL_HOST_PASSWORD), y DEFAULT_FROM_EMAIL. "
        "Si deseas deshabilitar esta validación explícitamente, setea ALLOW_NO_EMAIL_IN_PROD=true."
    )

EMAIL_REQUIRED_FOR_SIGNUP = _smtp_configured or (IS_PRODUCTION and not ALLOW_NO_EMAIL_IN_PROD)

# Verificación de email:
# - Producción: por defecto, obligatoria (si no está permitida la excepción).
# - Desarrollo: obligatoria solo si hay SMTP; si no, opcional (para no bloquear el flujo local).
ACCOUNT_EMAIL_VERIFICATION = (
    os.environ.get("ACCOUNT_EMAIL_VERIFICATION")
    or ("mandatory" if EMAIL_REQUIRED_FOR_SIGNUP else "optional")
)

ACCOUNT_UNIQUE_EMAIL = True if EMAIL_REQUIRED_FOR_SIGNUP else False

# allauth (nueva API)
ACCOUNT_LOGIN_METHODS = {"username"}
if ACCOUNT_UNIQUE_EMAIL:
    ACCOUNT_LOGIN_METHODS.add("email")

ACCOUNT_SIGNUP_FIELDS = [
    "email*" if EMAIL_REQUIRED_FOR_SIGNUP else "email",
    "username*",
    "password1*",
    "password2*",
]

ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_ADAPTER = "cba_app.allauth_adapter.SideoAccountAdapter"
ACCOUNT_FORMS = {
    "login": "cba_app.allauth_forms.AllauthLoginForm",
    "signup": "cba_app.allauth_forms.AllauthSignupForm",
}

# Email backend
if not _smtp_configured:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

    # Prioridad: SendGrid (recomendado en Render)
    if _sendgrid_api_key:
        EMAIL_HOST = "smtp.sendgrid.net"
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_HOST_USER = "apikey"
        EMAIL_HOST_PASSWORD = _sendgrid_api_key
    else:
        EMAIL_HOST = _email_host
        EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
        EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
        EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
        EMAIL_USE_TLS = _env_bool("DJANGO_EMAIL_USE_TLS", True)

    DEFAULT_FROM_EMAIL = _default_from_email or "no-reply@sideo.local"

if IS_PRODUCTION and not ALLOW_NO_EMAIL_IN_PROD:
    # Aseguramos remitente válido para proveedores tipo SendGrid.
    if not (globals().get("DEFAULT_FROM_EMAIL") or "").strip() or DEFAULT_FROM_EMAIL.endswith(".local"):
        raise ImproperlyConfigured(
            "DEFAULT_FROM_EMAIL inválido para producción. Configura un remitente real/verificado "
            "(por ejemplo, un Single Sender en SendGrid)."
        )

# Social login (Google). Activo solo si se setean estas variables.
_google_client_id = (os.environ.get("GOOGLE_CLIENT_ID") or "").strip()
_google_client_secret = (os.environ.get("GOOGLE_CLIENT_SECRET") or "").strip()
if _google_client_id and _google_client_secret:
    SOCIALACCOUNT_PROVIDERS = {
        "google": {
            "SCOPE": ["profile", "email"],
            "AUTH_PARAMS": {"access_type": "online"},
            "APP": {
                "client_id": _google_client_id,
                "secret": _google_client_secret,
                "key": "",
            },
        }
    }

# django-axes (anti brute force)
AXES_ENABLED = _env_bool("AXES_ENABLED", True)
AXES_FAILURE_LIMIT = int(os.environ.get("AXES_FAILURE_LIMIT", "5"))
AXES_COOLOFF_TIME = timedelta(
    minutes=int(os.environ.get("AXES_COOLOFF_MINUTES", "30"))
)
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]
AXES_RESET_ON_SUCCESS = True
AXES_USERNAME_FORM_FIELD = "login"  # allauth usa 'login' como campo de usuario/email


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if not DEBUG:
    # Nota: algunos assets de terceros y/o del admin pueden referenciar archivos
    # no presentes (p.ej. sourcemaps). Los storages "Compressed*" intentan abrir
    # todo para comprimir y pueden fallar el build. Preferimos un build estable.
    STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Límites de subida
# Algunos despliegues/proxies pueden manejar tamaños mayores, pero Django por defecto puede ser
# conservador en cuanto a cuánto cuerpo de request mantiene en memoria.
# Ajustable por variables de entorno para no hardcodear un único valor.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", str(25 * 1024 * 1024))
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE", str(5 * 1024 * 1024))
)

if os.environ.get("CLOUDINARY_URL"):
    # Cloudinary obligatorio: usar storage remoto para media.
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

    static_backend = (
        'whitenoise.storage.StaticFilesStorage'
        if not DEBUG
        else 'django.contrib.staticfiles.storage.StaticFilesStorage'
    )

    # Django moderno: STORAGES es la fuente principal para backends.
    STORAGES = {
        'default': {
            'BACKEND': DEFAULT_FILE_STORAGE,
        },
        'staticfiles': {
            'BACKEND': static_backend,
        },
    }

# Seguridad básica para producción detrás de proxy (Render)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Allauth: asegurar links https en correos, incluso detrás de proxy.
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])
if RENDER_EXTERNAL_HOSTNAME:
    render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

# --- OpenRouter (IA Asistente de decisión) ---

# --- Power BI ---
# URL del dashboard/reporte en Power BI (por ejemplo, un link de reporte o embed).
# Configurar como variable de entorno: POWER_BI_DASHBOARD_URL
POWER_BI_DASHBOARD_URL = os.environ.get("POWER_BI_DASHBOARD_URL", "")

# Token opcional para proteger los feeds JSON consumidos por Power BI.
# Configurar como variable de entorno: POWER_BI_FEED_TOKEN
POWER_BI_FEED_TOKEN = os.environ.get("POWER_BI_FEED_TOKEN", "")
# Configura la API key como variable de entorno: OPENROUTER_API_KEY
# Modelo por defecto: puedes cambiarlo con OPENROUTER_MODEL
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
OPENROUTER_MODEL = os.environ.get('OPENROUTER_MODEL', 'meta-llama/llama-3.2-3b-instruct:free')
OPENROUTER_TIMEOUT_SECONDS = float(os.environ.get('OPENROUTER_TIMEOUT_SECONDS', '30'))

# --- allauth-ui (UI para pantallas de auth) ---
ALLAUTH_UI_THEME = os.environ.get("ALLAUTH_UI_THEME", "light")
