# Generated by Django 6.0.2 on 2026-02-07 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de la alternativa (para evaluar costo versus ventaja).', max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('criterion_type', models.CharField(choices=[('MUST', 'Debe tener'), ('WANT', 'Desea tener')], default='MUST', help_text="Indica si el factor es 'Debe tener' o 'Desea tener'.", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción del atributo de esta alternativa para este factor.')),
                ('is_least_preferred', models.BooleanField(default=False, help_text='Marca si este es el atributo menos preferido para este factor.')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='cba_app.alternative')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='cba_app.criterion')),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción de la ventaja respecto al atributo menos preferido.')),
                ('importance', models.PositiveIntegerField(help_text='Puntaje de importancia asignado a esta ventaja.')),
                ('is_main', models.BooleanField(default=False, help_text='Marca si esta es la ventaja principal para esta alternativa.')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='cba_app.alternative')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='cba_app.criterion')),
            ],
        ),
    ]
