# Generated by Django 6.0.2 on 2026-02-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cba_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner_name', models.CharField(blank=True, max_length=200)),
                ('winner_total', models.PositiveIntegerField(default=0)),
                ('winner_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('winner_ratio', models.FloatField(blank=True, null=True)),
                ('data_json', models.TextField(blank=True, help_text='Datos de costo y total de ventajas usados en el gráfico.')),
            ],
        ),
    ]
