# Generated by Django 6.0.2 on 2026-02-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cba_app', '0002_cbaresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('OPENROUTER', 'OpenRouter')], default='OPENROUTER', max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, help_text='Id del modelo en OpenRouter (ej. meta-llama/llama-3.2-3b-instruct:free)', max_length=255)),
                ('timeout_seconds', models.FloatField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
