# Generated by Django 6.0.2 on 2026-02-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cba_app', '0004_default_openrouter_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedGuideLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Link compartido de guía',
                'verbose_name_plural': 'Links compartidos de guía',
            },
        ),
        migrations.AlterModelOptions(
            name='aiprovidersetting',
            options={'verbose_name': 'Configuración de IA', 'verbose_name_plural': 'Configuraciones de IA'},
        ),
        migrations.AlterField(
            model_name='aiprovidersetting',
            name='api_key',
            field=models.CharField(blank=True, help_text='Pega aquí tu API key del proveedor (se recomienda no exponerla fuera del Admin).', max_length=255),
        ),
    ]
