# Generated by Django 6.0.2 on 2026-02-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cba_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbaresult',
            name='power_bi_url',
            field=models.URLField(blank=True, help_text='URL del dashboard/reporte en Power BI para este proyecto (opcional).'),
        ),
    ]
