# Generated by Django 6.0.2 on 2026-02-20 02:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cba_app', '0009_sharedguidelink_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCBA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=255)),
                ('puesto', models.CharField(blank=True, max_length=150, null=True)),
                ('candidato', models.CharField(max_length=150)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ventaja', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_ventaja', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('recomendado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Resultado CBA (Power BI)',
                'verbose_name_plural': 'Resultados CBA (Power BI)',
                'db_table': 'resultados_cba',
                'indexes': [models.Index(fields=['proyecto'], name='resultados__proyect_2d1254_idx'), models.Index(fields=['puesto'], name='resultados__puesto_d698e5_idx'), models.Index(fields=['candidato'], name='resultados__candida_546acb_idx'), models.Index(fields=['fecha'], name='resultados__fecha_fc8bc4_idx'), models.Index(fields=['recomendado'], name='resultados__recomen_0cdb4a_idx')],
            },
        ),
    ]
