# Generated by Django 6.0.2 on 2026-02-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cba_app', '0010_resultadocba'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraficaCostoVentaja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proyectos', models.CharField(max_length=255)),
                ('puesto', models.CharField(blank=True, max_length=150, null=True)),
                ('candidatos', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ventaja', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Grafica de Costo/Ventaja (Power BI)',
                'verbose_name_plural': 'Grafica de Costo/Ventaja (Power BI)',
                'db_table': 'grafica_costo_ventaja',
                'indexes': [models.Index(fields=['proyectos'], name='grafica_cos_proyect_f83551_idx'), models.Index(fields=['puesto'], name='grafica_cos_puesto_46bd14_idx'), models.Index(fields=['candidatos'], name='grafica_cos_candida_ad2e0f_idx')],
            },
        ),
    ]
