# Generated by Django 6.0.2 on 2026-02-21

import cba_app.models
from cloudinary.models import CloudinaryField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cba_app", "0012_graficacostoventaja_result_resultadocba_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=CloudinaryField(
                "image",
                blank=True,
                null=True,
            ),
        ),
    ]
