# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cba_app", "0013_userprofile_avatar_cloudinary"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_name", models.CharField(blank=True, default="", max_length=512)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Guía (PDF)",
                "verbose_name_plural": "Guía (PDF)",
            },
        ),
    ]
