# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cba_app", "0014_guidedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidedocument",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="guidedocument",
            name="cloudinary_resource_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="guidedocument",
            name="cloudinary_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
