# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cba_app", "0015_guidedocument_cloudinary_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoCBARecomendado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "proyecto",
                    models.CharField(max_length=255),
                ),
                (
                    "puesto",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "candidato",
                    models.CharField(max_length=150),
                ),
                (
                    "costo",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "ventaja",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "costo_ventaja",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
                ),
                ("recomendado", models.BooleanField(default=True)),
                ("fecha", models.DateTimeField(default=timezone.now)),
                ("resumen_ia", models.TextField(blank=True)),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powerbi_resultados_recomendados",
                        to="cba_app.cbaresult",
                    ),
                ),
            ],
            options={
                "db_table": "resultados_cba_recomendados",
                "verbose_name": "Resultado CBA Recomendado (Power BI)",
                "verbose_name_plural": "Resultados CBA Recomendados (Power BI)",
                "indexes": [
                    models.Index(fields=["result"], name="cba_rec_result_idx"),
                    models.Index(fields=["proyecto"], name="cba_rec_proyecto_idx"),
                    models.Index(fields=["puesto"], name="cba_rec_puesto_idx"),
                    models.Index(fields=["candidato"], name="cba_rec_candidato_idx"),
                    models.Index(fields=["fecha"], name="cba_rec_fecha_idx"),
                ],
            },
        ),
    ]
