# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cba_app", "0016_resultadocbarecomendado"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerBISetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dashboard_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración Power BI",
                "verbose_name_plural": "Configuraciones Power BI",
            },
        ),
    ]
