# Generated by Copilot on 2026-02-23

"""PostgreSQL view for Power BI: grafica_costo_ventaja (public format).

Crea una VIEW con el formato exacto requerido:
  id, proyectos, puesto, candidatos, costo, ventaja, costo/ventaja, recomendado, resumen_ia

Nota: En desarrollo local este proyecto usa SQLite; allí esta migración es no-op.
"""

from django.db import migrations


POSTGRES_CREATE = """
CREATE OR REPLACE VIEW vw_powerbi_grafica_costo_ventaja_public AS
SELECT
    id,
    proyectos,
    puesto,
    candidatos,
    costo,
    ventaja,
    (costo / NULLIF(ventaja, 0)) AS \"costo/ventaja\",
    FALSE AS recomendado,
    NULL::text AS resumen_ia
FROM grafica_costo_ventaja
ORDER BY proyectos, puesto, candidatos, id
"""

POSTGRES_DROP = "DROP VIEW IF EXISTS vw_powerbi_grafica_costo_ventaja_public"


def _is_postgres(schema_editor) -> bool:
    return schema_editor.connection.vendor == "postgresql"


def create_view(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(POSTGRES_CREATE)


def drop_view(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(POSTGRES_DROP)


class Migration(migrations.Migration):

    dependencies = [
        ("cba_app", "0018_powerbi_views"),
    ]

    operations = [
        migrations.RunPython(create_view, reverse_code=drop_view),
    ]
