# Generated by Copilot on 2026-02-23

"""PostgreSQL view for Power BI: resultados_cba (public format).

Formato EXACTO requerido (solo estas columnas y en este orden):
  id, proyectos, puesto, candidatos, costo, ventaja, costo/ventaja, recomendado, resumen_ia

Nota: En desarrollo local este proyecto usa SQLite; allí esta migración es no-op.
"""

from django.db import migrations


POSTGRES_CREATE = """
CREATE OR REPLACE VIEW vw_powerbi_resultados_cba_public AS
SELECT
    id,
    proyecto AS proyectos,
    puesto,
    candidato AS candidatos,
    costo,
    ventaja,
    costo_ventaja AS \"costo/ventaja\",
    recomendado,
    NULL::text AS resumen_ia
FROM resultados_cba
ORDER BY proyecto, puesto, candidato, id
"""

POSTGRES_DROP = "DROP VIEW IF EXISTS vw_powerbi_resultados_cba_public"


def _is_postgres(schema_editor) -> bool:
    return schema_editor.connection.vendor == "postgresql"


def create_view(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(POSTGRES_CREATE)


def drop_view(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    schema_editor.execute(POSTGRES_DROP)


class Migration(migrations.Migration):

    dependencies = [
        ("cba_app", "0019_powerbi_grafica_public_view"),
    ]

    operations = [
        migrations.RunPython(create_view, reverse_code=drop_view),
    ]
